### ISSUE TITLE
pagination not return the correct value after filtering

### ISSUE THREAD

**Issue by prasetyowira** [lookinlab/adonis-lucid-filter#10]
Hello, 

I'm currently having a problem using pagination with this filter.
the total, perPage, page, and lastPage doesn't return the correct value after filtering. this is my source code

`const products = await Product.query().filter(query).paginate(page, 12)`

in my db it should return `{
total: 59,
  perPage: 12,
  page: '3',
  lastPage: 5,
}`

instead of `{
total: 400,
  perPage: 12,
  page: '3',
  lastPage: 34,
}`

here is my model filter code 

```
async subcategory (name) {
    const categoryQuery = await ProductCategory.findByOrFail('slug', name)
    const categoryId = categoryQuery.id
    return this.where('category_id', categoryId)
}
```

Adonis Version: 4.1.0
Lucid Version: 5.0.4
Adonis Filter Version: 1.0.3

**Comment by LookinGit** [comment]
Hi, @prasetyowira!
Methods of filter not be async, therefore return incorrect result. Try:
```js
subcategory (name) {
  return this.related('productCategory', 'slug', name)
}
```
