### ISSUE TITLE
Relationship based filtering

### ISSUE THREAD

**Issue by sorxrob** [lookinlab/adonis-lucid-filter#18]
Hi, first of all I just want to say this is a good module to easily filter data.

I have a question, how can you do something like this:

```javascript
const { training, participants, start_date } = request.get();

let q = Schedule.query();

if (training === 'true') {
  q = q.with('speakers');
}

if (participants === 'true') {
  q = q.with('speakers');
}

if (start_date) {
  q = q.where('start_date', '>=', start_date)
}

await q.fetch();
```

Basically what it does is when those params exist, it gets the related items. I checked the documentation and I only see a simple usage of relationship using the `with` method.

Is it something you can also do with this module? Thanks in advance.

**Comment by LookinGit** [comment]
Hi, @sorxrob. Thanks
Try it:

`app/ModelFilters/ScheduleFilter.js`
```js
'use strict';

const ModelFilter = use('ModelFilter');

class ScheduleFilter extends ModelFilter {
  training(value) {
    if (value !== 'true') return;
    this.with('speakers')
  }
  participants(value) {
    if (value !== 'true') return;
    this.with('participants')
  }
  start_date(value) {
    this.where('start_date', '>=', value)
  }
}

module.exports = ScheduleFilter;
```

```js
...
await Schedule.query()
  .filter(request.get())
  .fetch()
```

**Comment by sorxrob** [comment]
> Hi, @sorxrob. Thanks
> Try it:
> 
> `app/ModelFilters/ScheduleFilter.js`
> 
> ```js
> 'use strict';
> 
> const ModelFilter = use('ModelFilter');
> 
> class ScheduleFilter extends ModelFilter {
>   training(value) {
>     if (value !== 'true') return;
>     return this.with('speakers')
>   }
>   participants(value) {
>     if (value !== 'true') return;
>     return this.with('participants')
>   }
>   start_date(value) {
>     return this.where('start_date', '>=', value)
>   }
> }
> 
> module.exports = ScheduleFilter;
> ```
> 
> ```js
> ...
> await Schedule.query()
>   .filter(request.get())
>   .fetch()
> ```

Thank you for this. I'll try that and update you. Do you also have solution for dynamic expressions?

Something like:

```
start_date(value) {
   return this.where('start_date', 'MAKE THIS ONE DYNAMIC', value)
 }
```

Thanks again!

**Comment by LookinGit** [comment]
You can use method `input` for get additional query param:

```js
start_date(value) {
  const startDateExpression = this.input('startDateExpression', 'defaultValue')
  return this.where('start_date', startDateExpression, value)
}
```
but allow users send expressions is not safe...

better use some params:
```js
largerStartDate(value) {
  return this.where('start_date', '>=', value)
}
smallerStartDate(value) {
  return this.where('start_date', '<', value)
}
```

**Comment by sorxrob** [comment]
> You can use method `input` for get additional query param:
> 
> ```js
> start_date(value) {
>   const startDateExpression = this.input('startDateExpression', 'defaultValue')
>   return this.where('start_date', startDateExpression, value)
> }
> ```
> 
> but allow users send expressions is not safe... need validate before filtering
> 
> better use some params:
> 
> ```js
> largerStartDate(value) {
>   return this.where('start_date', '>=', value)
> }
> smallerStartDate(value) {
>   return this.where('start_date', '<', value)
> }
> ```

Understandable. Thank you again for your time. Keep it up!
