### ISSUE TITLE
Can't use filter in User model

### ISSUE THREAD

**Issue by ghmendonca** [lookinlab/adonis-lucid-filter#20]
For some reason the filter doesn't work in User model, the other models it works just fine.

I think it's not even passing through the filter functions defined in my UserFilter which extends ModelFilter, because if I put some console logs, it won't be executed.

My UserFilter:
```
const ModelFilter = use('ModelFilter')

class UserFilter extends ModelFilter {
    secure_id(secure_id) {
        return this.where('secure_id', secure_id)
    }

    full_name(full_name) {
        return this.where('full_name', full_name)
    }

    email(email) {
        return this.where('email', email)
    }

    type_doc(type_doc) {
        return this.where('type_doc', type_doc)
    }

    number_doc(number_doc) {
        return this.where('number_doc', number_doc)
    }

    cellphone(cellphone) {
        return this.where('cellphone', cellphone)
    }

    status(status) {
        return this.where('status', status)
    }

    status(role) {
        return this.where('role', role)
    }
}

module.exports = UserFilter
```

In the boot function inside my User model I'm adding the trait like that: `this.addTrait('@provider:Filterable', UserFilter)`

And finally in my UserService where I'm calling the filter function and I guarantee the filter is coming populated or I can just pass an object there and it won't work anyways:
```
static async getUsers(filter) {
    return (await User.query().filter(filter).fetch()).toJSON()
}
```

**Comment by LookinGit** [comment]
Hi, @ghmendonca.
Need more info or example your UserService.
Param `filter` into `getUsers` is Object? or instance UserFilter?

**Comment by LookinGit** [comment]
@ghmendonca 
change names methods to `camelCase` format:
- secure_id -> secureId
- full_name -> fullName
- type_doc -> typeDoc
...etc

**Comment by ghmendonca** [comment]
It is a plain object coming from graphql, I will leave below the code that is calling this function.

```
Query: {
        users: async (_, { filter }) => {
            return await UserService.getUsers(filter)
        },
        me: async (_, params, { user }) => {
            return user
        },
    },
```

My filter.graphql:
```
input UserFilter {
    secure_id: ID
    full_name: String
    email: String
    type_doc: TypeDoc
    number_doc: String
    cellphone: String
    slug: String
    status: Status
}
```

But as I said, doesn't matter, if I try to hard code the filter object it won't work, just like the example below:
```
static async getUsers() {
    return (await User.query().filter({full_name: 'test'}).fetch()).toJSON()
}
```

Also, I don't see why I should change to camel case since everything in my code is snake case, if I try to get user.fullName I'll probably get undefined (unless adonis is making some magic) since my database columns are all in snake case. Also, why my other models which are snake case and the code is exactly the same works? I have the same code for another model, of course the field names are different but the filter works..

That's why I think this is related only for the User model.

**Comment by LookinGit** [comment]
@ghmendonca, you need to use `camelCase` only in `UserFilter.js` names methods, because ModelFilter creates name of method from props names for call. Props of model User may not change.
[https://github.com/lookinlab/adonis-lucid-filter/blob/develop/src/Model/index.js#L191](url)

**Comment by ghmendonca** [comment]
Will try that in a bit and let you know if works or not
