### ISSUE TITLE
Filtering relationships with 'OR'

### ISSUE THREAD

**Issue by allanthomasof** [lookinlab/adonis-lucid-filter#21]
Hello, I'm trying to make a filter using 'this.related' but I needed it to bring records using 'OR' instead of 'AND' ... how can I do it?

It would be something like this:

`builder.orWhere(x.field, 'LIKE', `%${x.value}%`)`

**Comment by LookinGit** [comment]
Hi, @allanthomasof!
Method `related` will be appropriate when filtering by single rule.

You may use `whereHas`, example:
```js
xField(value) {
  return this.whereHas('relationship', builder => {
    builder.where('xField', 'LIKE', `%${value}%`
      .orWhere('yField', 'LIKE', `%${value}%`)
  })
}
```
