### ISSUE TITLE
Adonis 5 installation help needed.

### ISSUE THREAD

**Issue by soonzhi** [lookinlab/adonis-lucid-filter#28]
follow the steps to install lucid filter in adonis 5.
1) yarn add adonis-lucid-filter@alpha
2)  node ace invoke adonis-lucid-filter
  update    tsconfig.json { types += adonis-lucid-filter }
   update    .adonisrc.json { commands += adonis-lucid-filter/build/commands }
   update    .adonisrc.json { providers += adonis-lucid-filter } 
✔  create    ace-manifest.json

3) node ace make:filter Transaction
✔  create    app/Models/Filters/TransactionFilter.ts

open up TransactionFilter.ts, 
it has error on the import statement:
import { BaseModelFilter } from '@ioc:Adonis/Addons/LucidFilter'

error shown:
Cannot find module '@ioc:Adonis/Addons/LucidFilter' or its corresponding type declarations.ts(2307)

**Comment by soonzhi** [comment]
my package.json:
  "devDependencies": {
    "@adonisjs/assembler": "^2.1.5",
    "adonis-preset-ts": "^1.0.4",
    "pino-pretty": "^4.2.1",
    "typescript": "^4.0.2",
    "youch": "^2.0.10",
    "youch-terminal": "^1.0.0"
  },
  "dependencies": {
    "@adonisjs/ace": "^6.9.4",
    "@adonisjs/auth": "^4.3.1",
    "@adonisjs/core": "^5.0.0-preview-rc-1.12",
    "@adonisjs/fold": "^6.4.0",
    "@adonisjs/lucid": "^8.4.2",
    "@adonisjs/mail": "^4.2.2",
    "@adonisjs/view": "^2.0.9",
    "adonis-lucid-filter": "^2.0.0-rc8",
    "crypto-random-string": "^3.3.0",
    "luxon": "^1.25.0",
    "moment": "^2.28.0",
    "mysql": "^2.18.1",
    "phc-argon2": "^1.0.10",
    "proxy-addr": "^2.0.6",
    "reflect-metadata": "^0.1.13",
    "source-map-support": "^0.5.19",
    "uuid": "^8.3.0"
  }
}

**Comment by LookinGit** [comment]
Hi @soonzhi, try to restart you IDE and project

**Comment by soonzhi** [comment]
thanks bro,you save my day.
