### ISSUE TITLE
Global filters

### ISSUE THREAD

**Issue by jpkontreras** [lookinlab/adonis-lucid-filter#29]
I have a requirement where filters are sent in this format `filter[field]&filter[anotherfield]&etc...`
and i created a filter for the User model in adonisJS v5

```js
export default class UserFilter extends BaseModelFilter {
  public $query: ModelQueryBuilderContract<typeof User, User>;

  //"filter":{"email":"","firstname":"","fullname":"a"},"sort":["name,asc","id,desc"]}

  public filter(values: any) {
    Object.keys(values).map((key) => {
      this.$query.where(key, "LIKE", `%${values[key]}%`);
    });
  }

  public sort(values) {
    if (typeof values === "string") {
      const [col, order] = values.split(",");
      this.$query.orderBy(col, order);
    }

    if (typeof values === "object") {
      values.forEach((element) => {
        const [col, order] = element.split(",");
        this.$query.orderBy(col, order);
      });
    }
  }
}
```

This works great
 but i dont want to repeat this class for every single model in my app 
 How can i then make this class a "Generic" one and pass the model as a constructor 

I was thinking something like this

controller.js
```js
 public async index({ request }: HttpContextContract) {
    const { page = 1, size = 10, ...rest } = request.qs();
    const users = await GenericFilter<User>.filter(rest).paginate(page, size);
  //OR
    const users = await GenericFilter.filter(User, rest).paginate(page, size);
    return users;
  }
```
The implementation of the filter would have to follow one of the two cases 
Also there is the case that maybe i complicated the issue and there is a easy way .. Anyway thanks

**Comment by LookinGit** [comment]
Hi @jpkontreras

I don't think this use case often meets. You can create `GlobalFilter` and then set him for every filterable model or use as dynamic filter ([2nd param of `filter` method](https://github.com/lookinlab/adonis-lucid-filter#dynamic-filters)).

Example:

```js
// GlobalFilter.ts
export default class GlobalFilter extends BaseModelFilter {
  public $query: ModelQueryBuilderContract<typeof LucidModel, LucidModel>;
  
  // your methods
}
```
