### ISSUE TITLE
Add deleted_at in where to link tables

### ISSUE THREAD

**Issue by nurycaroline** [lookinlab/adonis-lucid-filter#30]
Hi
When using preload, I think that deleted_at should be added to all tables involved.
For example, if a link between book and author is removed, the search will still bring the link, because the deleted_at is for the Book table, I think I should add it to the author_book table as well.

**Comment by LookinGit** [comment]
Hi @nurycaroline. I think this issue for [adonis-lucid-soft-deletes](https://github.com/lookinlab/adonis-lucid-soft-deletes) :)
