### ISSUE TITLE
How to add check based on 2 fields. 

### ISSUE THREAD

**Issue by hsharma1996** [lookinlab/adonis-lucid-filter#34]
Requirement :- There are two fields in filter 1) Holiday number, 2) Reading number(1 OR 2). 
The filter is required to accept both the fields and make an AND condition of both using whereHas. 

Problem :- I have holiday defined on filter like 
**`  holiday(holiday: number) {
           this.$query.whereHas('holidays', (query) => query.wherePivot('holidays_id', holiday))
        }`**

How can I access reading number inside that ? 
I tried using this.$input but typesciprt error is coming saying 
readings does not exists on type object. 
Thanks :)

**Comment by LookinGit** [comment]
Hello, @hsharma1996
Did you try use `this.$input['readingNumber']` to avoid typescript errors?
