### ISSUE TITLE
filter seems not working when combined with wherehas

### ISSUE THREAD

**Issue by donnigundala** [lookinlab/adonis-lucid-filter#35]
im not sure this is an issue or something else.

my code something looks like this
````
........
const query = this.model.query()
query.whereHas('escalations', (builder) => {
    builder.whereIn('to_level', [2])
})
query.filter(params.filter)`
return query.paginate()
.........
````
the filter seems to be ignored (not working as expected) when there is a whereHas()

but when i remove/comment the whereHas() query part, everything filtered as expected.

maybe someone has any idea what's going on?

**Comment by LookinGit** [comment]
Hello, @donnigundala

Here have two ways:
- change call functions order on `filter().whereHas()` (filter method return QueryBuilder)
- define property `escalation` in filter

and try worked or no

**Comment by donnigundala** [comment]
thank for the reply.

i've try the first one filter still not filtering.

otw to try the second option.
