### ISSUE TITLE
Async support in `setup` and `filter method`s

### ISSUE THREAD

**Issue by ndianabasi** [lookinlab/adonis-lucid-filter#37]
Hi @LookinGit.

In my use case for Adonis Lucid Filter, there are need for supporting async `setup` and `filter` methods. What is the possibility of this being supported?

I've looked at the `BaseModel` and `Mixin` and it looks feasible. Or are there other reasons for not supporting `async` operations?

This an example of an async operation within a filter method:

```ts
  public async enterprises(ids?: string | string[]) {
    const relatedWorkspaces = await Workspace.query()
      .whereIn('workspaces.enterprise_id', this.getIds(ids))
      .select('id')

    this.$query.whereIn(
      'brands.workspace_id',
      relatedWorkspaces.map((workspace) => workspace.id)
    )
  }
```

I spent 2 days wondering while that particular method was not filtering properly while others work as expected. Until I realised that `async` method might not be supported by the plugin. 😂

**Comment by ndianabasi** [comment]
I just decided to try the `Database` class and it helped avoided the use of `async` operation:

```ts
  public enterprises(ids?: string | string[]) {
    this.$query.whereIn(
      'brands.workspace_id',
      Database.from('workspaces').whereIn('workspaces.enterprise_id', this.getIds(ids)).select('id')
    )
  }
```

I think this strategy is worth mentioning in the doc. Should I add it to the doc?

**Comment by LookinGit** [comment]
Hello @ndianabasi 
Nope, i don`t think what this need in docs.
This do apply for adonisjs and a work with him, not for this addon.

Same way your problem have a solution through a `whereHas` method and have a better description in adonisjs docs:
https://docs.adonisjs.com/guides/models/relationships#filter-by-relationships

example:
```ts
  public enterprises(ids?: string | string[]) {
    this.$query.whereHas('workspaces', (query) => {
      query.whereIn('enterprise_id', ids)
    }
  }
```

**Comment by ndianabasi** [comment]
Alright. I will be closing this.
