### ISSUE TITLE
Filter pattern

### ISSUE THREAD

**Issue by btxtiger** [lookinlab/adonis-lucid-filter#41]
I came across this package while searching for an equivalent migration from Laravel.
[Laravel-Query-Builder](https://github.com/spatie/laravel-query-builder) from Spatie supports URL filters by adding `?filter[name]=John`. How can I configure the package this way, so I could keep the existing URL structure?

**Comment by LookinGit** [comment]
Hello, @btxtiger 
If i understand you right, you need get your filter params from request and get they in filter model, example:

```ts
// Controller
public async index({ request }: HttpContextContract) {
  const { filter } = request.qs();
  const models = await YourModel.filter(filter).all();

  return models;
}
```

[More](https://docs.adonisjs.com/guides/request#query-string-and-route-params) about `request.qs()`

**Comment by btxtiger** [comment]
so basically I will have to build it by my own
The Laravel-Query-Builder supports filtering and including relations via query param in a single function call without any custom code.
